NASDAQ = {
    "NVDA": "Nvidia",
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "AMZN": "Amazon",
    "GOOG": "Alphabet Class C",
    "GOOGL": "Alphabet Class A",
    "META": "Meta Platforms",
    "TSLA": "Tesla",
    "AVGO": "Broadcom",
    "NFLX": "Netflix",
    "COST": "Costco",
    "ASML": "ASML Holding",
    "TMUS": "T-Mobile US",
    "CSCO": "Cisco Systems",
    "ISRG": "Intuitive Surgical",
    "AZN": "AstraZeneca",
    "LIN": "Linde",
    "PEP": "PepsiCo",
    "AMD": "Advanced Micro Devices",
    "QCOM": "Qualcomm",
    "ADBE": "Adobe",
    "TXN": "Texas Instruments",
    "INTU": "Intuit",
    "VZ": "Verizon",
    "BKNG": "Booking Holdings",
    "AMAT": "Applied Materials",
    "AMGN": "Amgen",
    "HON": "Honeywell",
    "PDD": "Pinduoduo",
    "CMCSA": "Comcast",
    "LRCX": "Lam Research",
    "LULU": "Lululemon Athletica",
    "MAR": "Marriott International",
    "MRVL": "Marvell Technology",
    "MELI": "Mercado Libre",
    "MCHP": "Microchip Technology",
    "MU": "Micron Technology",
    "MSTR": "MicroStrategy",
    "MDLZ": "Mondelez International",
    "MNST": "Monster Beverage",
    "NXPI": "NXP Semiconductors",
    "ORLY": "O’Reilly Automotive",
    "ODFL": "Old Dominion Freight Line",
    "ON": "Onsemi",
    "PCAR": "Paccar",
    "PLTR": "Palantir Technologies",
    "PANW": "Palo Alto Networks",
    "PAYX": "Paychex",
    "PYPL": "PayPal Holdings",
    "REGN": "Regeneron Pharmaceuticals"
}


NIFTY50 = {
    "ADANIPORTS": "Adani Ports and Special Economic Zone Ltd",
    "ASIANPAINT": "Asian Paints Ltd",
    "AXISBANK": "Axis Bank Ltd",
    "BAJAJ-AUTO": "Bajaj Auto Ltd",
    "BAJFINANCE": "Bajaj Finance Ltd",
    "BAJAJFINSV": "Bajaj Finserv Ltd",
    "BHARTIARTL": "Bharti Airtel Ltd",
    "BPCL": "Bharat Petroleum Corporation Ltd",
    "BRITANNIA": "Britannia Industries Ltd",
    "CIPLA": "Cipla Ltd",
    "COALINDIA": "Coal India Ltd",
    "DIVISLAB": "Divi's Laboratories Ltd",
    "DRREDDY": "Dr. Reddy's Laboratories Ltd",
    "EICHERMOT": "Eicher Motors Ltd",
    "GRASIM": "Grasim Industries Ltd",
    "HCLTECH": "HCL Technologies Ltd",
    "HDFCBANK": "HDFC Bank Ltd",
    "HDFCLIFE": "HDFC Life Insurance Company Ltd",
    "HEROMOTOCO": "Hero MotoCorp Ltd",
    "HINDALCO": "Hindalco Industries Ltd",
    "HINDUNILVR": "Hindustan Unilever Ltd",
    "ICICIBANK": "ICICI Bank Ltd",
    "INDUSINDBK": "IndusInd Bank Ltd",
    "INFY": "Infosys Ltd",
    "ITC": "ITC Ltd",
    "JSWSTEEL": "JSW Steel Ltd",
    "KOTAKBANK": "Kotak Mahindra Bank Ltd",
    "LT": "Larsen & Toubro Ltd",
    "M&M": "Mahindra & Mahindra Ltd",
    "MARUTI": "Maruti Suzuki India Ltd",
    "NESTLEIND": "Nestle India Ltd",
    "NTPC": "NTPC Ltd",
    "ONGC": "Oil & Natural Gas Corporation Ltd",
    "POWERGRID": "Power Grid Corporation of India Ltd",
    "RELIANCE": "Reliance Industries Ltd",
    "SBILIFE": "SBI Life Insurance Company Ltd",
    "SBIN": "State Bank of India",
    "SHREECEM": "Shree Cement Ltd",
    "SUNPHARMA": "Sun Pharmaceutical Industries Ltd",
    "TATACONSUM": "Tata Consumer Products Ltd",
    "TATAMOTORS": "Tata Motors Ltd",
    "TATASTEEL": "Tata Steel Ltd",
    "TCS": "Tata Consultancy Services Ltd",
    "TECHM": "Tech Mahindra Ltd",
    "TITAN": "Titan Company Ltd",
    "ULTRACEMCO": "UltraTech Cement Ltd",
    "UPL": "UPL Ltd",
    "WIPRO": "Wipro Ltd"
}
